services:
  mysql:
    image: mysql:8.4
    container_name: student_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: REMOVED_PASSWORD
      MYSQL_DATABASE: studentdb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pREMOVED_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: student_app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: REMOVED_PASSWORD